module.exports = {
  "kind": "Listing",
  "data": {
    "modhash": "p7ttr6t9dj73cfc187fc1ceac449c4c7925ec9bd47a4d10e2e",
    "whitelist_status": "all_ads",
    "children": [
      {
        "kind": "t3",
        "data": {
          "domain": "self.aww",
          "approved_at_utc": null,
          "mod_reason_by": null,
          "banned_by": null,
          "num_reports": null,
          "subreddit_id": "t5_2qh1o",
          "thumbnail_width": null,
          "subreddit": "aww",
          "selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;We get 20 creddits to hand out this year.  We&amp;#39;re going to do 10 categories, with 1st and 2nd place each getting 1 creddit.  &lt;/p&gt;\n\n&lt;p&gt;The categories are:&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;p&gt;Overall cutest post&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Cutest cat/kitten&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Cutest dog/puppy&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Cutest human&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Cutest other (anything not a cat/dog/human)&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Cutest multiple species (cat+dog/cat+human/dog+human/dog+cat+human/etc)&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Cutest underappreciated submission (&amp;lt;10,000 upvotes on the post)&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Best comment&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Silliest post&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Cutest fail&lt;/p&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;Post your nominations as a response to the category comment below, and we&amp;#39;ll do a voting thread once the year is over.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
          "selftext": "We get 20 creddits to hand out this year.  We're going to do 10 categories, with 1st and 2nd place each getting 1 creddit.  \n\nThe categories are:\n\n* Overall cutest post\n\n* Cutest cat/kitten\n\n* Cutest dog/puppy\n\n* Cutest human\n\n* Cutest other (anything not a cat/dog/human)\n\n* Cutest multiple species (cat+dog/cat+human/dog+human/dog+cat+human/etc)\n\n* Cutest underappreciated submission (&lt;10,000 upvotes on the post)\n\n* Best comment\n\n* Silliest post\n\n* Cutest fail\n\nPost your nominations as a response to the category comment below, and we'll do a voting thread once the year is over.",
          "likes": null,
          "suggested_sort": null,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "link_flair_text": null,
          "id": "7jjnz5",
          "banned_at_utc": null,
          "mod_reason_title": null,
          "view_count": null,
          "archived": false,
          "clicked": false,
          "media_embed": {},
          "report_reasons": null,
          "author": "N8theGr8",
          "num_crossposts": 0,
          "saved": false,
          "mod_reports": [],
          "can_mod_post": false,
          "is_crosspostable": true,
          "pinned": false,
          "score": 176,
          "approved_by": null,
          "over_18": false,
          "hidden": false,
          "thumbnail": "self",
          "edited": false,
          "link_flair_css_class": null,
          "author_flair_css_class": null,
          "contest_mode": false,
          "gilded": 0,
          "downs": 0,
          "brand_safe": true,
          "secure_media_embed": {},
          "removal_reason": null,
          "author_flair_text": null,
          "stickied": true,
          "can_gild": true,
          "thumbnail_height": null,
          "parent_whitelist_status": "all_ads",
          "name": "t3_7jjnz5",
          "spoiler": false,
          "permalink": "/r/aww/comments/7jjnz5/bestof_raww_2017_nominations_thread/",
          "subreddit_type": "public",
          "locked": false,
          "hide_score": false,
          "created": 1513204917,
          "url": "https://www.reddit.com/r/aww/comments/7jjnz5/bestof_raww_2017_nominations_thread/",
          "whitelist_status": "all_ads",
          "quarantine": false,
          "title": "Bestof /r/Aww, 2017 nominations thread!",
          "created_utc": 1513176117,
          "subreddit_name_prefixed": "r/aww",
          "ups": 176,
          "media": null,
          "num_comments": 82,
          "is_self": true,
          "visited": false,
          "mod_note": null,
          "is_video": false,
          "distinguished": null
        }
      },
      {
        "kind": "t3",
        "data": {
          "domain": "reddit.com",
          "approved_at_utc": null,
          "mod_reason_by": null,
          "banned_by": null,
          "num_reports": null,
          "subreddit_id": "t5_2qh1o",
          "thumbnail_width": 140,
          "subreddit": "aww",
          "selftext_html": null,
          "selftext": "",
          "likes": null,
          "suggested_sort": null,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "link_flair_text": null,
          "id": "7k0q0k",
          "banned_at_utc": null,
          "mod_reason_title": null,
          "view_count": null,
          "archived": false,
          "clicked": false,
          "media_embed": {},
          "report_reasons": null,
          "author": "N8theGr8",
          "num_crossposts": 0,
          "saved": false,
          "mod_reports": [],
          "can_mod_post": false,
          "is_crosspostable": true,
          "pinned": false,
          "score": 129,
          "approved_by": null,
          "over_18": false,
          "hidden": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://i.redditmedia.com/4xFezp8qybWigpg6WN5gkAuI39AIPdv4jdHijFU4_ns.jpg?s=8598544207619a3020f808583e28b4c4",
                  "width": 256,
                  "height": 256
                },
                "resolutions": [
                  {
                    "url": "https://i.redditmedia.com/4xFezp8qybWigpg6WN5gkAuI39AIPdv4jdHijFU4_ns.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=19f81c159c3852ca87417e2d2edde0b0",
                    "width": 108,
                    "height": 108
                  },
                  {
                    "url": "https://i.redditmedia.com/4xFezp8qybWigpg6WN5gkAuI39AIPdv4jdHijFU4_ns.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=2b071d25ede17deadf68cb9b7db13230",
                    "width": 216,
                    "height": 216
                  }
                ],
                "variants": {},
                "id": "KR8oJeB8ComfEPX0bkCe_p2L73IOmk0sTCsyNlfXSNg"
              }
            ],
            "enabled": false
          },
          "thumbnail": "https://b.thumbs.redditmedia.com/lysXL2rWDiJJUeCcw5ruERApH0dpKTvwv1oTbEZEaMA.jpg",
          "edited": false,
          "link_flair_css_class": null,
          "author_flair_css_class": null,
          "contest_mode": false,
          "gilded": 0,
          "downs": 0,
          "brand_safe": true,
          "secure_media_embed": {},
          "removal_reason": null,
          "post_hint": "link",
          "author_flair_text": null,
          "stickied": true,
          "can_gild": true,
          "thumbnail_height": 140,
          "parent_whitelist_status": "all_ads",
          "name": "t3_7k0q0k",
          "spoiler": false,
          "permalink": "/r/aww/comments/7k0q0k/rcuddleroll_raww_subreddit_of_the_week/",
          "subreddit_type": "public",
          "locked": false,
          "hide_score": false,
          "created": 1513383781,
          "url": "https://www.reddit.com/r/cuddleroll/",
          "whitelist_status": "all_ads",
          "quarantine": false,
          "title": "/r/CuddleRoll: /r/Aww Subreddit of the Week",
          "created_utc": 1513354981,
          "subreddit_name_prefixed": "r/aww",
          "ups": 129,
          "media": null,
          "num_comments": 4,
          "is_self": false,
          "visited": false,
          "mod_note": null,
          "is_video": false,
          "distinguished": null
        }
      },
      {
        "kind": "t3",
        "data": {
          "domain": "i.redd.it",
          "approved_at_utc": null,
          "mod_reason_by": null,
          "banned_by": null,
          "num_reports": null,
          "subreddit_id": "t5_2qh1o",
          "thumbnail_width": 140,
          "subreddit": "aww",
          "selftext_html": null,
          "selftext": "",
          "likes": null,
          "suggested_sort": null,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": true,
          "link_flair_text": null,
          "id": "7lgxy6",
          "banned_at_utc": null,
          "mod_reason_title": null,
          "view_count": null,
          "archived": false,
          "clicked": false,
          "media_embed": {},
          "report_reasons": null,
          "author": "sorelj",
          "num_crossposts": 1,
          "saved": false,
          "mod_reports": [],
          "can_mod_post": false,
          "is_crosspostable": true,
          "pinned": false,
          "score": 44258,
          "approved_by": null,
          "over_18": false,
          "hidden": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://i.redditmedia.com/6un3jiQHTF7TQhL_q3n2xpn_xonIxiYeXzUme7Cx2zs.jpg?s=078289f870f3eb98d41a1c6db18c5568",
                  "width": 720,
                  "height": 960
                },
                "resolutions": [
                  {
                    "url": "https://i.redditmedia.com/6un3jiQHTF7TQhL_q3n2xpn_xonIxiYeXzUme7Cx2zs.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=50a57c8ccdea80d29cca842967863e07",
                    "width": 108,
                    "height": 144
                  },
                  {
                    "url": "https://i.redditmedia.com/6un3jiQHTF7TQhL_q3n2xpn_xonIxiYeXzUme7Cx2zs.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=fe4a7c734a7d662b2e1c7c7374ac253d",
                    "width": 216,
                    "height": 288
                  },
                  {
                    "url": "https://i.redditmedia.com/6un3jiQHTF7TQhL_q3n2xpn_xonIxiYeXzUme7Cx2zs.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=1994935f95f678935cf3cb02233df6ed",
                    "width": 320,
                    "height": 426
                  },
                  {
                    "url": "https://i.redditmedia.com/6un3jiQHTF7TQhL_q3n2xpn_xonIxiYeXzUme7Cx2zs.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=8fe6cd45178362a168d0ada5adcf9e96",
                    "width": 640,
                    "height": 853
                  }
                ],
                "variants": {},
                "id": "deDsehkqN3jMFeSraqjXSIDtVYNynCWJNOuq1NcNp-E"
              }
            ],
            "enabled": true
          },
          "thumbnail": "https://b.thumbs.redditmedia.com/ocX_hQBq5ibq3nW3URl3RKEAxtteBvPol89IH2ZEiGU.jpg",
          "edited": false,
          "link_flair_css_class": null,
          "author_flair_css_class": null,
          "contest_mode": false,
          "gilded": 0,
          "downs": 0,
          "brand_safe": true,
          "secure_media_embed": {},
          "removal_reason": null,
          "post_hint": "image",
          "author_flair_text": null,
          "stickied": false,
          "can_gild": true,
          "thumbnail_height": 140,
          "parent_whitelist_status": "all_ads",
          "name": "t3_7lgxy6",
          "spoiler": false,
          "permalink": "/r/aww/comments/7lgxy6/the_utterly_disappointed_look_the_hamster_gave_me/",
          "subreddit_type": "public",
          "locked": false,
          "hide_score": false,
          "created": 1513971761,
          "url": "https://i.redd.it/sg8f9pftkg501.jpg",
          "whitelist_status": "all_ads",
          "quarantine": false,
          "title": "The utterly disappointed look the hamster gave me when we took too long to find the lid for her ball...",
          "created_utc": 1513942961,
          "subreddit_name_prefixed": "r/aww",
          "ups": 44258,
          "media": null,
          "num_comments": 502,
          "is_self": false,
          "visited": false,
          "mod_note": null,
          "is_video": false,
          "distinguished": null
        }
      }, 
      {
        "kind": "t3",
        "data": {
          "domain": "i.redd.it",
          "approved_at_utc": null,
          "mod_reason_by": null,
          "banned_by": null,
          "num_reports": null,
          "subreddit_id": "t5_2qh1o",
          "thumbnail_width": 140,
          "subreddit": "aww",
          "selftext_html": null,
          "selftext": "",
          "likes": null,
          "suggested_sort": null,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": true,
          "link_flair_text": null,
          "id": "7lhco7",
          "banned_at_utc": null,
          "mod_reason_title": null,
          "view_count": null,
          "archived": false,
          "clicked": false,
          "media_embed": {},
          "report_reasons": null,
          "author": "croak_dream",
          "num_crossposts": 0,
          "saved": false,
          "mod_reports": [],
          "can_mod_post": false,
          "is_crosspostable": true,
          "pinned": false,
          "score": 8479,
          "approved_by": null,
          "over_18": false,
          "hidden": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://i.redditmedia.com/cRwLDhbfEaUeDsgXVHVdpa7dpc0mY0xgoFo0Ioi_slc.jpg?s=a0d3248c070baae498eeca81dd8b12e1",
                  "width": 2048,
                  "height": 1536
                },
                "resolutions": [
                  {
                    "url": "https://i.redditmedia.com/cRwLDhbfEaUeDsgXVHVdpa7dpc0mY0xgoFo0Ioi_slc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=17f225bf4e10915f8f98fe3265ea7edc",
                    "width": 108,
                    "height": 81
                  },
                  {
                    "url": "https://i.redditmedia.com/cRwLDhbfEaUeDsgXVHVdpa7dpc0mY0xgoFo0Ioi_slc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=6fa709b8ab4dbb67587f4df3026615b7",
                    "width": 216,
                    "height": 162
                  },
                  {
                    "url": "https://i.redditmedia.com/cRwLDhbfEaUeDsgXVHVdpa7dpc0mY0xgoFo0Ioi_slc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=0fe5def2eaa911c7b0214788700525a8",
                    "width": 320,
                    "height": 240
                  },
                  {
                    "url": "https://i.redditmedia.com/cRwLDhbfEaUeDsgXVHVdpa7dpc0mY0xgoFo0Ioi_slc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=85803edf28b1b9efc01367fc9e908f29",
                    "width": 640,
                    "height": 480
                  },
                  {
                    "url": "https://i.redditmedia.com/cRwLDhbfEaUeDsgXVHVdpa7dpc0mY0xgoFo0Ioi_slc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=d07084887751b05c6d5c016979374d2b",
                    "width": 960,
                    "height": 720
                  },
                  {
                    "url": "https://i.redditmedia.com/cRwLDhbfEaUeDsgXVHVdpa7dpc0mY0xgoFo0Ioi_slc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=f7449860f1d27e53efd506353819fe70",
                    "width": 1080,
                    "height": 810
                  }
                ],
                "variants": {},
                "id": "68ZxmaZ5d4Fg3s7BuIz-QVqTmNy49GJ8ydB-Cx_3f_Y"
              }
            ],
            "enabled": true
          },
          "thumbnail": "https://b.thumbs.redditmedia.com/pcp5M-BNmTXZDWEsr2Z6oC67RP9h3n3zXeQl2jISfPE.jpg",
          "edited": false,
          "link_flair_css_class": null,
          "author_flair_css_class": null,
          "contest_mode": false,
          "gilded": 0,
          "downs": 0,
          "brand_safe": true,
          "secure_media_embed": {},
          "removal_reason": null,
          "post_hint": "image",
          "author_flair_text": null,
          "stickied": false,
          "can_gild": true,
          "thumbnail_height": 105,
          "parent_whitelist_status": "all_ads",
          "name": "t3_7lhco7",
          "spoiler": false,
          "permalink": "/r/aww/comments/7lhco7/one_of_my_newest_buddies_reddit_meet_murph/",
          "subreddit_type": "public",
          "locked": false,
          "hide_score": false,
          "created": 1513977202,
          "url": "https://i.redd.it/c4gsi8ed4h501.jpg",
          "whitelist_status": "all_ads",
          "quarantine": false,
          "title": "One of my newest buddies. Reddit. Meet Murph.",
          "created_utc": 1513948402,
          "subreddit_name_prefixed": "r/aww",
          "ups": 8479,
          "media": null,
          "num_comments": 113,
          "is_self": false,
          "visited": false,
          "mod_note": null,
          "is_video": false,
          "distinguished": null
        }
      },
      {
        "kind": "t3",
        "data": {
          "domain": "imgur.com",
          "approved_at_utc": null,
          "mod_reason_by": null,
          "banned_by": null,
          "num_reports": null,
          "subreddit_id": "t5_2qh1o",
          "thumbnail_width": 140,
          "subreddit": "aww",
          "selftext_html": null,
          "selftext": "",
          "likes": null,
          "suggested_sort": null,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "link_flair_text": null,
          "id": "7likds",
          "banned_at_utc": null,
          "mod_reason_title": null,
          "view_count": null,
          "archived": false,
          "clicked": false,
          "media_embed": {},
          "report_reasons": null,
          "author": "Aceripper",
          "num_crossposts": 0,
          "saved": false,
          "mod_reports": [],
          "can_mod_post": false,
          "is_crosspostable": true,
          "pinned": false,
          "score": 7272,
          "approved_by": null,
          "over_18": false,
          "hidden": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://i.redditmedia.com/YMkAuOJodWbSIWwOE6PROjZiOxhqHKvTDethpuen52I.jpg?s=94cfe5793da1ed1a0b77193ee5fe647f",
                  "width": 3840,
                  "height": 2160
                },
                "resolutions": [
                  {
                    "url": "https://i.redditmedia.com/YMkAuOJodWbSIWwOE6PROjZiOxhqHKvTDethpuen52I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=8e927b527b1726a888c27f50d463962d",
                    "width": 108,
                    "height": 60
                  },
                  {
                    "url": "https://i.redditmedia.com/YMkAuOJodWbSIWwOE6PROjZiOxhqHKvTDethpuen52I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=56267f8668719e8b8abeb673d316cfb6",
                    "width": 216,
                    "height": 121
                  },
                  {
                    "url": "https://i.redditmedia.com/YMkAuOJodWbSIWwOE6PROjZiOxhqHKvTDethpuen52I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=1b98fe31737c3a509c90f71b14c67481",
                    "width": 320,
                    "height": 180
                  },
                  {
                    "url": "https://i.redditmedia.com/YMkAuOJodWbSIWwOE6PROjZiOxhqHKvTDethpuen52I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=1a11db7ee05cd65e891d7b93e8385e0f",
                    "width": 640,
                    "height": 360
                  },
                  {
                    "url": "https://i.redditmedia.com/YMkAuOJodWbSIWwOE6PROjZiOxhqHKvTDethpuen52I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=a94cc019c1c95a2040cf069e8a31af72",
                    "width": 960,
                    "height": 540
                  },
                  {
                    "url": "https://i.redditmedia.com/YMkAuOJodWbSIWwOE6PROjZiOxhqHKvTDethpuen52I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=a3bbc3523b56588e3c79aeff317d4075",
                    "width": 1080,
                    "height": 607
                  }
                ],
                "variants": {},
                "id": "UqrqQ85bLxDTIKZ9Qy7OqJwl89rdne7Xb4SWR5ObGGk"
              }
            ],
            "enabled": false
          },
          "thumbnail": "https://b.thumbs.redditmedia.com/QSUuDy1hqlBua2SuFYIGZ6KbhHJ7SnuRpddrGbu_DwI.jpg",
          "edited": false,
          "link_flair_css_class": null,
          "author_flair_css_class": null,
          "contest_mode": false,
          "gilded": 0,
          "downs": 0,
          "brand_safe": true,
          "secure_media_embed": {},
          "removal_reason": null,
          "post_hint": "link",
          "author_flair_text": null,
          "stickied": false,
          "can_gild": true,
          "thumbnail_height": 78,
          "parent_whitelist_status": "all_ads",
          "name": "t3_7likds",
          "spoiler": false,
          "permalink": "/r/aww/comments/7likds/never_believed_it_was_possible_14_months_after/",
          "subreddit_type": "public",
          "locked": false,
          "hide_score": false,
          "created": 1513989828,
          "url": "https://imgur.com/XSrP1fZ",
          "whitelist_status": "all_ads",
          "quarantine": false,
          "title": "Never believed it was possible, 14 months after going missing, our beautiful boy comes home three days before Christmas",
          "created_utc": 1513961028,
          "subreddit_name_prefixed": "r/aww",
          "ups": 7272,
          "media": null,
          "num_comments": 184,
          "is_self": false,
          "visited": false,
          "mod_note": null,
          "is_video": false,
          "distinguished": null
        }
      },
    ],
    "after": "t3_7li4qp",
    "before": null
  }
}